/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateRecordingRequest = IDL.Record({
  'title' : IDL.Text,
  'audioBlobRef' : IDL.Text,
  'language' : IDL.Text,
  'durationSeconds' : IDL.Float64,
});
export const RecordingId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const TranscriptStatus = IDL.Variant({
  'pending' : IDL.Null,
  'error' : IDL.Null,
  'complete' : IDL.Null,
  'processing' : IDL.Null,
});
export const RecordingInfo = IDL.Record({
  'id' : RecordingId,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'audioBlobRef' : IDL.Text,
  'language' : IDL.Text,
  'updatedAt' : Timestamp,
  'durationSeconds' : IDL.Float64,
  'transcript' : IDL.Text,
  'transcriptStatus' : TranscriptStatus,
});
export const RefineMode = IDL.Variant({
  'summarize' : IDL.Null,
  'grammarFix' : IDL.Null,
  'rewrite' : IDL.Null,
  'removeFiller' : IDL.Null,
});
export const RefineRequest = IDL.Record({
  'mode' : RefineMode,
  'text' : IDL.Text,
});
export const RefineResult = IDL.Record({ 'refinedText' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateTranscriptRequest = IDL.Record({
  'id' : RecordingId,
  'status' : TranscriptStatus,
  'transcript' : IDL.Text,
});

export const idlService = IDL.Service({
  'createRecording' : IDL.Func([CreateRecordingRequest], [RecordingInfo], []),
  'deleteRecording' : IDL.Func([RecordingId], [IDL.Bool], []),
  'getRecording' : IDL.Func([RecordingId], [IDL.Opt(RecordingInfo)], ['query']),
  'listRecordings' : IDL.Func([], [IDL.Vec(RecordingInfo)], ['query']),
  'refineText' : IDL.Func([RefineRequest], [RefineResult], []),
  'transcribeRecording' : IDL.Func([RecordingId], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateRecordingTitle' : IDL.Func([RecordingId, IDL.Text], [IDL.Bool], []),
  'updateTranscript' : IDL.Func([UpdateTranscriptRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateRecordingRequest = IDL.Record({
    'title' : IDL.Text,
    'audioBlobRef' : IDL.Text,
    'language' : IDL.Text,
    'durationSeconds' : IDL.Float64,
  });
  const RecordingId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const TranscriptStatus = IDL.Variant({
    'pending' : IDL.Null,
    'error' : IDL.Null,
    'complete' : IDL.Null,
    'processing' : IDL.Null,
  });
  const RecordingInfo = IDL.Record({
    'id' : RecordingId,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'audioBlobRef' : IDL.Text,
    'language' : IDL.Text,
    'updatedAt' : Timestamp,
    'durationSeconds' : IDL.Float64,
    'transcript' : IDL.Text,
    'transcriptStatus' : TranscriptStatus,
  });
  const RefineMode = IDL.Variant({
    'summarize' : IDL.Null,
    'grammarFix' : IDL.Null,
    'rewrite' : IDL.Null,
    'removeFiller' : IDL.Null,
  });
  const RefineRequest = IDL.Record({ 'mode' : RefineMode, 'text' : IDL.Text });
  const RefineResult = IDL.Record({ 'refinedText' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateTranscriptRequest = IDL.Record({
    'id' : RecordingId,
    'status' : TranscriptStatus,
    'transcript' : IDL.Text,
  });
  
  return IDL.Service({
    'createRecording' : IDL.Func([CreateRecordingRequest], [RecordingInfo], []),
    'deleteRecording' : IDL.Func([RecordingId], [IDL.Bool], []),
    'getRecording' : IDL.Func(
        [RecordingId],
        [IDL.Opt(RecordingInfo)],
        ['query'],
      ),
    'listRecordings' : IDL.Func([], [IDL.Vec(RecordingInfo)], ['query']),
    'refineText' : IDL.Func([RefineRequest], [RefineResult], []),
    'transcribeRecording' : IDL.Func([RecordingId], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateRecordingTitle' : IDL.Func([RecordingId, IDL.Text], [IDL.Bool], []),
    'updateTranscript' : IDL.Func([UpdateTranscriptRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };