/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateRecordingRequest {
  'title' : string,
  'audioBlobRef' : string,
  'language' : string,
  'durationSeconds' : number,
}
export type RecordingId = bigint;
export interface RecordingInfo {
  'id' : RecordingId,
  'title' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'audioBlobRef' : string,
  'language' : string,
  'updatedAt' : Timestamp,
  'durationSeconds' : number,
  'transcript' : string,
  'transcriptStatus' : TranscriptStatus,
}
export type RefineMode = { 'summarize' : null } |
  { 'grammarFix' : null } |
  { 'rewrite' : null } |
  { 'removeFiller' : null };
export interface RefineRequest { 'mode' : RefineMode, 'text' : string }
export interface RefineResult { 'refinedText' : string }
export type Timestamp = bigint;
export type TranscriptStatus = { 'pending' : null } |
  { 'error' : null } |
  { 'complete' : null } |
  { 'processing' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateTranscriptRequest {
  'id' : RecordingId,
  'status' : TranscriptStatus,
  'transcript' : string,
}
export type UserId = Principal;
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createRecording' : ActorMethod<[CreateRecordingRequest], RecordingInfo>,
  'deleteRecording' : ActorMethod<[RecordingId], boolean>,
  'getRecording' : ActorMethod<[RecordingId], [] | [RecordingInfo]>,
  'listRecordings' : ActorMethod<[], Array<RecordingInfo>>,
  'refineText' : ActorMethod<[RefineRequest], RefineResult>,
  'transcribeRecording' : ActorMethod<[RecordingId], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateRecordingTitle' : ActorMethod<[RecordingId, string], boolean>,
  'updateTranscript' : ActorMethod<[UpdateTranscriptRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];