/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RefineRequest {
    mode: RefineMode;
    text: string;
}
export type RecordingId = bigint;
export interface RefineResult {
    refinedText: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface RecordingInfo {
    id: RecordingId;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    audioBlobRef: string;
    language: string;
    updatedAt: Timestamp;
    durationSeconds: number;
    transcript: string;
    transcriptStatus: TranscriptStatus;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CreateRecordingRequest {
    title: string;
    audioBlobRef: string;
    language: string;
    durationSeconds: number;
}
export interface UpdateTranscriptRequest {
    id: RecordingId;
    status: TranscriptStatus;
    transcript: string;
}
export enum RefineMode {
    summarize = "summarize",
    grammarFix = "grammarFix",
    rewrite = "rewrite",
    removeFiller = "removeFiller"
}
export enum TranscriptStatus {
    pending = "pending",
    error = "error",
    complete = "complete",
    processing = "processing"
}
export interface backendInterface {
    createRecording(req: CreateRecordingRequest): Promise<RecordingInfo>;
    deleteRecording(id: RecordingId): Promise<boolean>;
    getRecording(id: RecordingId): Promise<RecordingInfo | null>;
    listRecordings(): Promise<Array<RecordingInfo>>;
    refineText(req: RefineRequest): Promise<RefineResult>;
    transcribeRecording(id: RecordingId): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateRecordingTitle(id: RecordingId, title: string): Promise<boolean>;
    updateTranscript(req: UpdateTranscriptRequest): Promise<boolean>;
}
import type { RecordingId as _RecordingId, RecordingInfo as _RecordingInfo, RefineMode as _RefineMode, RefineRequest as _RefineRequest, Timestamp as _Timestamp, TranscriptStatus as _TranscriptStatus, UpdateTranscriptRequest as _UpdateTranscriptRequest, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createRecording(arg0: CreateRecordingRequest): Promise<RecordingInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecording(arg0);
                return from_candid_RecordingInfo_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecording(arg0);
            return from_candid_RecordingInfo_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRecording(arg0: RecordingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecording(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecording(arg0);
            return result;
        }
    }
    async getRecording(arg0: RecordingId): Promise<RecordingInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecording(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecording(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRecordings(): Promise<Array<RecordingInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecordings();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecordings();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async refineText(arg0: RefineRequest): Promise<RefineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.refineText(to_candid_RefineRequest_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refineText(to_candid_RefineRequest_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transcribeRecording(arg0: RecordingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.transcribeRecording(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transcribeRecording(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateRecordingTitle(arg0: RecordingId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecordingTitle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecordingTitle(arg0, arg1);
            return result;
        }
    }
    async updateTranscript(arg0: UpdateTranscriptRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTranscript(to_candid_UpdateTranscriptRequest_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTranscript(to_candid_UpdateTranscriptRequest_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_RecordingInfo_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordingInfo): RecordingInfo {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_TranscriptStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TranscriptStatus): TranscriptStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecordingInfo]): RecordingInfo | null {
    return value.length === 0 ? null : from_candid_RecordingInfo_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordingId;
    title: string;
    owner: _UserId;
    createdAt: _Timestamp;
    audioBlobRef: string;
    language: string;
    updatedAt: _Timestamp;
    durationSeconds: number;
    transcript: string;
    transcriptStatus: _TranscriptStatus;
}): {
    id: RecordingId;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    audioBlobRef: string;
    language: string;
    updatedAt: Timestamp;
    durationSeconds: number;
    transcript: string;
    transcriptStatus: TranscriptStatus;
} {
    return {
        id: value.id,
        title: value.title,
        owner: value.owner,
        createdAt: value.createdAt,
        audioBlobRef: value.audioBlobRef,
        language: value.language,
        updatedAt: value.updatedAt,
        durationSeconds: value.durationSeconds,
        transcript: value.transcript,
        transcriptStatus: from_candid_TranscriptStatus_n3(_uploadFile, _downloadFile, value.transcriptStatus)
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    error: null;
} | {
    complete: null;
} | {
    processing: null;
}): TranscriptStatus {
    return "pending" in value ? TranscriptStatus.pending : "error" in value ? TranscriptStatus.error : "complete" in value ? TranscriptStatus.complete : "processing" in value ? TranscriptStatus.processing : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecordingInfo>): Array<RecordingInfo> {
    return value.map((x)=>from_candid_RecordingInfo_n1(_uploadFile, _downloadFile, x));
}
function to_candid_RefineMode_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RefineMode): _RefineMode {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_RefineRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RefineRequest): _RefineRequest {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TranscriptStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TranscriptStatus): _TranscriptStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTranscriptRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTranscriptRequest): _UpdateTranscriptRequest {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RecordingId;
    status: TranscriptStatus;
    transcript: string;
}): {
    id: _RecordingId;
    status: _TranscriptStatus;
    transcript: string;
} {
    return {
        id: value.id,
        status: to_candid_TranscriptStatus_n13(_uploadFile, _downloadFile, value.status),
        transcript: value.transcript
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mode: RefineMode;
    text: string;
}): {
    mode: _RefineMode;
    text: string;
} {
    return {
        mode: to_candid_RefineMode_n9(_uploadFile, _downloadFile, value.mode),
        text: value.text
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RefineMode): {
    summarize: null;
} | {
    grammarFix: null;
} | {
    rewrite: null;
} | {
    removeFiller: null;
} {
    return value == RefineMode.summarize ? {
        summarize: null
    } : value == RefineMode.grammarFix ? {
        grammarFix: null
    } : value == RefineMode.rewrite ? {
        rewrite: null
    } : value == RefineMode.removeFiller ? {
        removeFiller: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TranscriptStatus): {
    pending: null;
} | {
    error: null;
} | {
    complete: null;
} | {
    processing: null;
} {
    return value == TranscriptStatus.pending ? {
        pending: null
    } : value == TranscriptStatus.error ? {
        error: null
    } : value == TranscriptStatus.complete ? {
        complete: null
    } : value == TranscriptStatus.processing ? {
        processing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
